# Generated by Django 5.2.3 on 2026-06-23 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0002_roll_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roll',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='roll',
            name='bet',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='roll',
            name='game_type',
            field=models.CharField(choices=[('classic', 'Classic Dice'), ('lucky7', 'Lucky 7'), ('jackpot', 'Jackpot')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='roll',
            name='winnings',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=1000)),
                ('total_won', models.IntegerField(default=0)),
                ('total_spent', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
