# Generated by Django 5.2.3 on 2026-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0003_alter_roll_options_roll_bet_roll_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_bonus',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
